name: "Nix Shell"
on:
    pull_request:
    push:
jobs:
    shell:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2.3.4
            - uses: cachix/install-nix-action@v12
            - uses: cachix/cachix-action@v8
              with:
                  name: ibizaman
                  authToken: "${{ secrets.CACHIX_IBIZAMAN_AUTHTOKEN }}"
            - run: nix-build shell.nix
